"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Category, Product } from "@/types/store";

function validImage(value?: string) { try { const url = new URL(value ?? ""); return ["res.cloudinary.com", "images.unsplash.com"].includes(url.hostname) ? url.toString() : ""; } catch { return ""; } }

export function CollectionsRail({ categories, products, selected }: { categories: Category[]; products: Product[]; selected: string }) { const router = useRouter(); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); async function create() { if (!name.trim()) return; setBusy(true); const response = await fetch("/api/admin/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim() }) }); if (response.ok) { setName(""); router.refresh(); } setBusy(false); } const count = (id: string) => products.filter((product) => product.category_id === id).length; return <aside className="collections-rail"><div className="rail-heading"><h2>Collections</h2></div>
<div className="quick-collection"> </div><div className="rail-collection-list">{categories.map((category) => { const image = validImage(category.image_url); return <article className={selected === category.slug ? "rail-collection-card active" : "rail-collection-card"} key={category.id} onClick={() => router.push(`/admin/products?collection=${category.slug}`)}><div className="rail-card-image">{image ? <img src={image} alt="" /> : <span>{category.name.charAt(0).toUpperCase()}</span>}</div><div className="rail-card-content"><strong>{category.name}</strong><small>{count(category.id)} products</small><span className={category.active ? "status status-live" : "status"}>{category.active ? "Active" : "Hidden"}</span></div><button type="button" className="rail-edit" aria-label={`Edit ${category.name}`} onClick={(event) => { event.stopPropagation(); router.push(`/admin/products?collectionEdit=${category.id}`); }}>✎</button></article>; })}<button className="rail-new-card" type="button" onClick={() => router.push("/admin/products?new=1")}>+ Create collection</button></div></aside>; }
