"use client";

// Product editor client boundary.

import { useEffect, useState } from "react";
import type { Category, Product } from "@/types/store";
import { ImageUploadField } from "./image-upload-field";

export function ProductDrawer({ product, categories, onClose, onSaved }: { product?: Product; categories: Category[]; onClose: () => void; onSaved: (product?: Product) => void }) {
  const [form, setForm] = useState({ name: product?.name ?? "", description: product?.description ?? "", category_id: product?.category_id ?? "", currency: product?.currency ?? "DZD", price: String(product?.price ?? ""), stock: String(product?.stock ?? ""), active: product?.active ?? true, featured: product?.featured ?? false, image_url: product?.image_url ?? "", image_public_id: product?.image_public_id ?? "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const onKey = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [onClose]);
  const set = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.name.trim() || !form.category_id || form.price === "" || form.stock === "") { setError("Name, category, price and stock are required."); return; } setBusy(true); setError(""); const response = await fetch("/api/admin/products", { method: product ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(product ? { productId: product.id, price: Number(form.price), stock: Number(form.stock), active: form.active, featured: form.featured } : { ...form, price: Number(form.price), stock: Number(form.stock) }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to save product."); setBusy(false); return; } setBusy(false); onSaved(result.product ?? { ...product, ...form, price: Number(form.price), stock: Number(form.stock) } as Product); onClose(); }
  return <div className="drawer-overlay" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="product-drawer" role="dialog" aria-modal="true" aria-label={product ? "Edit product" : "Create product"}><div className="drawer-header"><div><h2>{product ? "Edit product" : "New product"}</h2></div><button className="icon-button" type="button" aria-label="Close" onClick={onClose}>×</button></div><form className="drawer-form" onSubmit={submit}><ImageUploadField url={form.image_url} publicId={form.image_public_id} onChange={(url, publicId) => { set("image_url", url); set("image_public_id", publicId); }} /><label>Name<input required value={form.name} onChange={(event) => set("name", event.target.value)} /></label><label>Description<textarea rows={3} value={form.description} onChange={(event) => set("description", event.target.value)} /></label><div className="form-row"><label>Category<select required value={form.category_id} onChange={(event) => set("category_id", event.target.value)}><option value="">Choose category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Currency<select value={form.currency} onChange={(event) => set("currency", event.target.value)}><option>DZD</option><option>EUR</option><option>USD</option></select></label></div><div className="form-row"><label>Price<input type="number" min="0" inputMode="decimal" value={form.price} onChange={(event) => set("price", event.target.value)} /></label><label>Stock<input type="number" min="0" inputMode="numeric" value={form.stock} onChange={(event) => set("stock", event.target.value)} /></label></div><div className="drawer-toggles"><label className="toggle-label"><input type="checkbox" checked={form.active} onChange={(event) => set("active", event.target.checked)} /><span /> Active</label><label className="toggle-label"><input type="checkbox" checked={form.featured} onChange={(event) => set("featured", event.target.checked)} /><span /> Featured</label></div>{error && <p className="form-error">{error}</p>}<footer className="drawer-footer"><button className="button sheet-reset" type="button" onClick={onClose}>Cancel</button><button className="button button-dark" disabled={busy}>{busy ? "Saving..." : product ? "Save changes" : "Create product"}</button></footer></form></aside></div>;
}
