"use client";

import { useMemo, useState } from "react";
import type { Category } from "@/types/store";
import { AdminList, AdminStatus } from "@/components/admin/admin-page";
import { CategoryEditor } from "./category-editor";
import { CategoryForm } from "./category-form";

export function CollectionsManager({ initialCategories, initialCreate = false }: { initialCategories: Category[]; initialCreate?: boolean }) { const [search, setSearch] = useState(""); const [showCreate, setShowCreate] = useState(initialCreate); const [activeOnly, setActiveOnly] = useState("all"); const [toast, setToast] = useState(""); const filtered = useMemo(() => initialCategories.filter((category) => (!search || `${category.name} ${category.slug} ${category.description}`.toLowerCase().includes(search.toLowerCase())) && (activeOnly === "all" || activeOnly === "active" && category.active || activeOnly === "inactive" && !category.active)), [initialCategories, search, activeOnly]); function created() { setShowCreate(false); setToast("Collection created"); window.setTimeout(() => setToast(""), 2500); } return <><div className="collections-toolbar"><div className="products-search-wrap"><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search collections..." aria-label="Search collections" />{search && <button className="search-clear" type="button" aria-label="Clear search" onClick={() => setSearch("")}>×</button>}</div><select value={activeOnly} onChange={(event) => setActiveOnly(event.target.value)} aria-label="Filter collections"><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><span className="product-count">{filtered.length} collections</span></div>{showCreate && <CategoryForm onCreated={created} onClose={() => setShowCreate(false)} />}<AdminList empty={<div className="product-empty"><h2>No collections yet</h2><p>Create a collection before adding products.</p><button className="button button-dark" type="button" onClick={() => setShowCreate(true)}>+ Create collection</button></div>}><div className="collection-card-grid">{filtered.map((category) => <article className="collection-card" key={category.id}><div className="collection-card-image">{category.image_url ? <img src={category.image_url} alt="" /> : <span aria-hidden="true">✦</span>}</div><div className="collection-card-body"><div className="collection-card-heading"><div><p className="eyebrow">/{category.slug}</p><h2>{category.name}</h2></div><AdminStatus active={category.active} /></div><p>{category.description || "No description yet."}</p><CategoryEditor category={category} /></div></article>)}</div></AdminList>{toast && <div className="admin-toast" role="status">{toast}</div>}</>; }
